// Supabase client configuration

import { createClient } from '@supabase/supabase-js';
import { env } from '$env/dynamic/public';

// Create a single supabase client for the browser
// Default to empty strings during build time, will be populated at runtime
const supabaseUrl = env.PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = env.PUBLIC_SUPABASE_ANON_KEY || '';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database helper types
export type Tables<T extends keyof Database['public']['Tables']> =
	Database['public']['Tables'][T]['Row'];
export type Inserts<T extends keyof Database['public']['Tables']> =
	Database['public']['Tables'][T]['Insert'];
export type Updates<T extends keyof Database['public']['Tables']> =
	Database['public']['Tables'][T]['Update'];

// This will be auto-generated by Supabase CLI (or manually defined)
export type Database = {
	public: {
		Tables: {
			players: {
				Row: {
					email: string;
					display_name: string;
					created_at: string;
					last_seen: string;
				};
				Insert: {
					email: string;
					display_name: string;
					created_at?: string;
					last_seen?: string;
				};
				Update: {
					email?: string;
					display_name?: string;
					created_at?: string;
					last_seen?: string;
				};
			};
			games: {
				Row: {
					id: string;
					host_email: string;
					status: string;
					direction: number;
					current_player_index: number;
					created_at: string;
					last_activity: string;
					winner_email: string | null;
				};
				Insert: {
					id?: string;
					host_email: string;
					status?: string;
					direction?: number;
					current_player_index?: number;
					created_at?: string;
					last_activity?: string;
					winner_email?: string | null;
				};
				Update: {
					id?: string;
					host_email?: string;
					status?: string;
					direction?: number;
					current_player_index?: number;
					created_at?: string;
					last_activity?: string;
					winner_email?: string | null;
				};
			};
			game_players: {
				Row: {
					id: string;
					game_id: string;
					player_email: string;
					player_order: number;
					hand: any; // JSONB
					uno_declared: boolean;
					joined_at: string;
				};
				Insert: {
					id?: string;
					game_id: string;
					player_email: string;
					player_order: number;
					hand?: any;
					uno_declared?: boolean;
					joined_at?: string;
				};
				Update: {
					id?: string;
					game_id?: string;
					player_email?: string;
					player_order?: number;
					hand?: any;
					uno_declared?: boolean;
					joined_at?: string;
				};
			};
			game_invitations: {
				Row: {
					id: string;
					game_id: string;
					invitee_email: string;
					status: string;
					created_at: string;
				};
				Insert: {
					id?: string;
					game_id: string;
					invitee_email: string;
					status?: string;
					created_at?: string;
				};
				Update: {
					id?: string;
					game_id?: string;
					invitee_email?: string;
					status?: string;
					created_at?: string;
				};
			};
			game_state: {
				Row: {
					game_id: string;
					draw_pile: any; // JSONB
					discard_pile: any; // JSONB
					current_color: string | null;
					updated_at: string;
				};
				Insert: {
					game_id: string;
					draw_pile: any;
					discard_pile: any;
					current_color?: string | null;
					updated_at?: string;
				};
				Update: {
					game_id?: string;
					draw_pile?: any;
					discard_pile?: any;
					current_color?: string | null;
					updated_at?: string;
				};
			};
			game_actions: {
				Row: {
					id: string;
					game_id: string;
					player_email: string;
					action_type: string;
					action_data: any; // JSONB
					created_at: string;
				};
				Insert: {
					id?: string;
					game_id: string;
					player_email: string;
					action_type: string;
					action_data: any;
					created_at?: string;
				};
				Update: {
					id?: string;
					game_id?: string;
					player_email?: string;
					action_type?: string;
					action_data?: any;
					created_at?: string;
				};
			};
		};
	};
};
